server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zyz
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: mybatis/mapper/UserMapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl